package com.redkite.core.domain;

public enum EnforcerStatus {
    ENFORCER_NOT_CONFIGURED,
    ENFORCER_CONFIGURED_NO_CONVERGENCE_RULES,
    ENFORCER_RUN_PASSED,
    ENFORCER_RUN_FAILED_WITH_FINDINGS,
    ENFORCER_RUN_FAILED_UNAVAILABLE
}
